config/routes.rb
Rails.application.routes.draw do
  get 'contents/newsletter'

  get 'contents/index'


  get 'static_pages/about_us'

  get 'static_pages/agreement'

  get 'static_pages/specific_trade'

  get 'top/index'

  devise_for :users
  resources :users, only: :show
  resources :categories, shallow: true, only: [:index, :show] do
    resources :questions, only: [:index, :show ]
  end

  get 'search' => 'questions#search'
  get 'question' => 'questions#product'
  get 'list' => 'top#show'

  root 'top#index'


end

app/models/category.rb
class Category < ActiveRecord::Base
  enum level: { large: 0, middle: 1, small: 2 }
  has_many :categories
  belongs_to :category
  has_many :questions
end

app/models/content.rb
class Content < ActiveRecord::Base
end

app/models/myqa.rb
class Myqa < ActiveRecord::Base
end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :category
  has_many   :relations
end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :family_name, presence: true, length: { maximum: 10 }
  validates :first_name, presence: true, length: { maximum: 10 }
  validates :company_name, presence: true, length: { maximum: 20 }
  validates :company_zyusho, presence: true, length: { maximum: 30 }

  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create }

  validates :agree, acceptance: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_out_path_for(resource)
    '/users/sign_in' # サインアウト後のリダイレクト先URL
  end

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:family_name, :first_name, :company_name, :company_zyusho])
  end




end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
    @category = Category.where(level: 'large' )
  end

  def show
    @category = Category.find(params[:id])

    @nuber1 = 4
    @questionf1 = Question.find(@nuber1)
    @titlef1 = @questionf1.title

    @nuber2 = 4
    @questionf2 = Question.find(@nuber2)
    @titlef2 = @questionf2.title

    @nuber3 = 4
    @questionf3 = Question.find(@nuber3)
    @titlef3 = @questionf3.title

    @nuber4 = 4
    @questionf4 = Question.find(@nuber4)
    @titlef4 = @questionf4.title

    @nuber5 = 4
    @questionf5 = Question.find(@nuber5)
    @titlef5 = @questionf5.title

    @nuber6 = 4
    @questionf6 = Question.find(@nuber6)
    @titlef6 = @questionf6.title

    @nuber7 = 4
    @questionf7 = Question.find(@nuber7)
    @titlef7 = @questionf7.title
    

  end


end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  def newsletter
    @newsletters = Newsletter.all
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :authenticate_user!, except: :index

  def index
    @category = Category.find params[:category_id]
    @questions = @category.questions
  end

  def show
    @question = Question.find params[:id]
    # @question1 = Relation.find_by(quest: @question.id)
    # @question2 = Question.find_by(id: @question1.relation_quest)
  end

  def search
    @products = Question.where('title LIKE(?)', "%#{params[:keyword]}%")
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def about_us
  end

  def agreement
  end

  def specific_trade
  end

end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
    @question1 = Question.find(1)
    @title1 = @question1.title
    @category1 = Category.find_by(id: @question1.category_id)
    @categorylevel1 = @category1.category_id
    @categoryname1  = Category.find_by(id: @categorylevel1)

    @question2 = Question.find(2)
    @title2 = @question2.title
    @category2 = Category.find_by(id: @question2.category_id)
    @categorylevel2 = @category2.category_id
    @categoryname2  = Category.find_by(id: @categorylevel2)

    @question3 = Question.find(3)
    @title3 = @question3.title
    @category3 = Category.find_by(id: @question3.category_id)
    @categorylevel3 = @category3.category_id
    @categoryname3  = Category.find_by(id: @categorylevel3)

    @question4 = Question.find(4)
    @title4 = @question4.title
    @category4 = Category.find_by(id: @question4.category_id)
    @categorylevel4 = @category4.category_id
    @categoryname4  = Category.find_by(id: @categorylevel4)


    @nuber1 = 4
    @questionf1 = Question.find(@nuber1)
    @titlef1 = @questionf1.title

    @nuber2 = 4
    @questionf2 = Question.find(@nuber2)
    @titlef2 = @questionf2.title

    @nuber3 = 4
    @questionf3 = Question.find(@nuber3)
    @titlef3 = @questionf3.title

    @nuber4 = 4
    @questionf4 = Question.find(@nuber4)
    @titlef4 = @questionf4.title

    @nuber5 = 4
    @questionf5 = Question.find(@nuber5)
    @titlef5 = @questionf5.title

    @nuber6 = 4
    @questionf6 = Question.find(@nuber6)
    @titlef6 = @questionf6.title

    @nuber7 = 4
    @questionf7 = Question.find(@nuber7)
    @titlef7 = @questionf7.title

  end

  def show

    @questions = Question.page(params[:page]).per(3)

  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/index.html.erb

<link rel='stylesheet' href='css/tcategoriesindex.css' type='text/css' media='all' />

<% @category.each do |category| %>
<p><%= link_to category.name, category_path(category) %> <p>
<% end %>

app/views/categories/show.html.erb
<!-- 画像部分ランダムにしたい -->
<link rel='stylesheet' href='css/categoriesshow.css' type='text/css' media='all' />


<h2 class='link'><img src="<%= asset_path "title/categorylist.png" %>" /></h2>

<% @category.categories.each do |category| %>
<ul>
  <li class='link'>・<%= link_to category.name, category_questions_path(category), :class => 'link'  %></li>
</ul>
<% end %>


<!-- ▽side -->
<div id="sidecateshow">
  <h2><img src="<%= asset_path "t_rec.png" %>"/></h2>
  <dl>
    <dt><img src="<%= asset_path "sum1.jpg" %>"/></dt>
    <dd>
      <p><a href="/questions/<%= @nuber1 %>", class="fev"><%=  @titlef1 %></a></p>
    </dd>
    <dt><img src="<%= asset_path "sum2.jpg" %>"/></dt>
    <dd>
      <p><a href="/questions/<%= @nuber2 %>", class="fev"><%=  @titlef2 %></a></p>
    </dd>
    <dt><img src="<%= asset_path "sum3.jpg" %>"/></dt>
    <dd>
      <p><a href="/questions/<%= @nuber3 %>", class="fev"><%=  @titlef3 %></a></p>
    </dd>
    <dt><img src="<%= asset_path "sum4.jpg" %>"/></dt>
    <dd>
      <p><a href="/questions/<%= @nuber4 %>", class="fev"><%=  @titlef4 %></a></p>
    </dd>
    <dt><img src="<%= asset_path "sum5.jpg" %>"/></dt>
    <dd>
      <p><a href="/questions/<%= @nuber5 %>", class="fev"><%=  @titlef5 %></a></p>
    </dd>
    <dt><img src="<%= asset_path "sum1.jpg" %>"/></dt>
    <dd>
      <p><a href="/questions/<%= @nuber6 %>", class="fev"><%=  @titlef6 %></a></p>
    </dd>
    <dt><img src="<%= asset_path "sum2.jpg" %>"/></dt>
    <dd>
      <p><a href="/questions/<%= @nuber7 %>", class="fev"><%=  @titlef7 %></a></p>
    </dd>
  </dl>
</div>
<!-- ▲side -->

app/views/contents/index.html.erb
<link rel='stylesheet' href='css/contents.css' type='text/css' media='all' />


<h3 class='link'><img src="<%= asset_path "title/contents.png" %>" /></h3>

<a class="categorylist"><%= link_to 'News letter', 'newsletter', :class => 'categorylist' %></a>

app/views/contents/newsletter.html.erb
<h3 class='link'><img src="<%= asset_path "title/newsletter.png" %>" /></h3>



<div id="main">
  <% @newsletters.each do |newsletter| %>
  <p class='newsletter'>・<%= link_to newsletter, newsletter.title, :class => 'newsletter' %></p>
  <% end %>
</div>

app/views/questions/index.html.erb
<!-- 画像部分ランダムにしたい -->

<link rel='stylesheet' href='css/questionindex.css' type='text/css' media='all' />


<h2><img src="<%= asset_path "title.png" %>"/></h2>


<% @category.categories.each do |category| %>
<ul>
<li class="questionindex">・<%= link_to category.name, category_questions_path(category), :class => 'questionindex' %></li>
</ul>
<% end %>

<% @questions.each do |question| %>
<ul>
  <li class="questionindex">・<%= link_to question.title, question, :class => 'questionindex'  %></li>
</ul>
<% end %>

app/views/questions/search.html.erb
<h2>QAを検索</h2>
  <%= form_tag('/search', method: :get) do %>
    <input class="search__query" name="keyword" placeholder="キーワードで検索" type="text" value=""><button class="btn-search" title="検索" type="submit"><i class="icon-search icon-4x"></i></button></input>
  <% end %>
<form accept-charset="utf-8" action="/" class="js-search-submit" method="get">
</form>


<% @products.each do |product| %>
  <p><%= link_to product.title, product %> <p>
    <% end %>


ランキング一覧など

app/views/questions/show.html.erb
<h3 class='link'><img src="<%= asset_path "title/title.png" %>" /></h3>
<p class='questiontitle' ><%= @question.title  %></p>

<h3 class='link'><img src="<%= asset_path "title/question.png" %>" /></h3>
<p class='questionque' ><%= @question.que %></p>

<h3 class='link'><img src="<%= asset_path "title/answer.png" %>" /></h3>
<p></p>
<p class='questionans' ><%= @question.answer %></p>

app/views/static_pages/about_us.html.erb
<link rel='stylesheet' href='css/about_us.css' type='text/css' media='all' />

<h2 class='link'><img src="<%= asset_path "title/aboutus.png" %>" /></h2>

<p class='aboutus'>MANETECHは、「専門情報を書籍からWEBへ」をビジョンとするメディアです。</p>
<p class='aboutus'>今まで、書籍上にしかないような専門情報をWEB上に掲載していき、税理士一人一人がよりお客様に価値のあるものを提供することができる</p>
<p class='aboutus'>環境を創造することを目的としており、MANATECHにしかない価値を提供するメディアを目指します。</p>

<p class='aboutus'>また、会社担当者が利用することにより、簡単な疑問は自己解決し、難題な事項のみ税理士に確認をする環境を整えていくことも目的としています。</p>

<p class='aboutus'>税金のみならず、会計、経営等の情報について、どんどん増やしていく方針ですので、今後をお楽しみにしてください。</p>

<p class='aboutuscontact'>・MANETECHへのお問い合わせ先</p>
<p class='aboutusmail'>[a]</p>
<p class='aboutusmail'>[a]を＠に変更してください。</p>

<p class='linkservice'></p>

<h2 ><img src="<%= asset_path "title/service.png" %>" /></h2>

<p class='aboutus'>mana techが運営しているサービスは大きく分けて２つになります。</p>

<p class='aboutustitle'>・QAについて</p>
<p class='aboutus2'>「書籍にしかない専門情報をWEBへ」を合言葉に　　サービスです。</p>
<p class='aboutus2'>税理士、公認会計士の方はもちろん、一般企業の経理・財務で仕事をするのにあたり必要な税の知識をQA方式にまとめたものになります。</p>
<p class='aboutus2'>内容については、適宜アップデートしていき、増加させていく予定で、現時点で約２，０００以上のQAをご用意しております。</p>
<p class='aboutus2'>現在の内容は税務のみになりますが、今後は経営、財務分析、資金調達などの内容も発信していきますのでもお楽しみに…</p>

<p class='aboutus2'>サンプルのリンク</p>

<p class='aboutustitle2'>・NewsLetter</p>
<p class='aboutus2'>税務や経営などに関する情報をまとめたものをワード形式でご用意しております。</p>
<p class='aboutus2'>そのときの旬やひとつの事柄をシリーズ化したものをご用意してます。</p>
<p class='aboutus2'>タイトル、税理士事務所名を変更するだけで、時間をかけずにオリジナルの資料を作成することが可能になります。</p>
<p class='aboutus2'>お客様に配るのもよし、職員の勉強用によし、もちろん自分自身の勉強用にもよし。</p>
<p class='aboutus2'>このような紙媒体を用いることにより、最新情報を顧問先に提供するだけではなく、コミュニケーションツールのひとつとしてご活用ください。</p>

<p class='aboutus2'>サンプルファイルのリンク</p>


<h2 class='link'><img src="<%= asset_path "title/price.png" %>" /></h2>


<p class='aboutus3'>これだけの内容なのに料金は年間税込で9,980円（一年契約　月契約だと998円）</p>


<p></p>

app/views/static_pages/specific_trade.html.erb
<link rel='stylesheet' href='css/specific_trade.css' type='text/css' media='all' />

<h3 class='link'><img src="<%= asset_path "title/specific_trade.png" %>" /></h3>

app/views/top/index.html.erb
<!-- 画像部分ランダムにしたい -->

  <!-- ▽main -->
  <div id="main">
    <h2><img src="<%= asset_path "title.png" %>"/></h2>
    <dl>
      <dt><img src="<%= asset_path "pic1.jpg" %>"/></dt>
      <dd>
        <h3><%= link_to @title1, '/questions/1', :class => 'title' %></h3>
        <p class="category"><%= link_to @categoryname1.name, '/categories/1', :class => 'categories' %></p>
      </dd>
    </dl>

    <dl>
      <dt><img src="<%= asset_path "pic2.jpg" %>"/></dt>
      <dd>
        <h3><%= link_to @title2, '/questions/2', :class => 'title' %></h3>
        <p class="category"><%= link_to @categoryname1.name, '/categories/1', :class => 'categories' %></p>
      </dd>
    </dl>

    <dl>
      <dt><img src="<%= asset_path "pic3.jpg" %>"/></dt>
      <dd>
        <h3><%= link_to @title3, '/questions/3', :class => 'title' %></h3>
        <p class="category"><%= link_to @categoryname1.name, '/categories/1', :class => 'categories' %></p>
      </dd>
    </dl>

    <dl>
      <dt><img src="<%= asset_path "pic4.jpg" %>"/></dt>
      <dd>
        <h3><%= link_to @title4, '/questions/4', :class => 'title' %></h3>
        <p class="category"><%= link_to @categoryname1.name, '/categories/1', :class => 'categories' %></p>
      </dd>
    </dl>
    <p class="list"><a href="/list/"><img src="<%= asset_path "bt_list.png" %>"/></a></p>
  </div>
  <!-- ▲main -->

  <!-- ▽side -->
  <div id="side">
    <h2><img src="<%= asset_path "t_rec.png" %>"/></h2>
    <dl>
      <dt><img src="<%= asset_path "sum1.jpg" %>"/></dt>
      <dd>
        <p><a href="/questions/<%= @nuber1 %>", class="fev"><%=  @titlef1 %></a></p>
      </dd>
      <dt><img src="<%= asset_path "sum2.jpg" %>"/></dt>
      <dd>
        <p><a href="/questions/<%= @nuber2 %>", class="fev"><%=  @titlef2 %></a></p>
      </dd>
      <dt><img src="<%= asset_path "sum3.jpg" %>"/></dt>
      <dd>
        <p><a href="/questions/<%= @nuber3 %>", class="fev"><%=  @titlef3 %></a></p>
      </dd>
      <dt><img src="<%= asset_path "sum4.jpg" %>"/></dt>
      <dd>
        <p><a href="/questions/<%= @nuber4 %>", class="fev"><%=  @titlef4 %></a></p>
      </dd>
      <dt><img src="<%= asset_path "sum5.jpg" %>"/></dt>
      <dd>
        <p><a href="/questions/<%= @nuber5 %>", class="fev"><%=  @titlef5 %></a></p>
      </dd>
      <dt><img src="<%= asset_path "sum1.jpg" %>"/></dt>
      <dd>
        <p><a href="/questions/<%= @nuber6 %>", class="fev"><%=  @titlef6 %></a></p>
      </dd>
      <dt><img src="<%= asset_path "sum2.jpg" %>"/></dt>
      <dd>
        <p><a href="/questions/<%= @nuber7 %>", class="fev"><%=  @titlef7 %></a></p>
      </dd>
    </dl>
  </div>
  <!-- ▲side -->

app/views/top/show.html.erb
<!-- 画像部分ランダムにしたい -->

<link rel='stylesheet' href='css/topshow.css' type='text/css' media='all' />




<h2><img src="<%= asset_path "title.png" %>"/></h2>


<div id="main">
    <% @questions.each do |question| %>
      <h3 class="topshow">・<%= link_to question.title, question, :class => 'titleshow' %></h3>
      <% end %>
      <%= paginate(@questions) %>
</div>

app/views/users/show.html.erb
<div class="user_page">
  <header class="user_page-header">
    <div class="yjContainer">
      <a href="">
        <h2><%=  current_user.family_name %> <span>さんのマイページ</span></h2>
      </a>
    </div>
  </header>


準備中